apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
  labels:
    app: {{ .Release.Name }}
    component: paperless
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.documents }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ .Release.Name }}
    component: paperless
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: 2Gi
