{{- $secretName := printf "%s-secrets" .Release.Name }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ $secretName}}
    labels:
        app: {{ .Release.Name }}
type: Opaque
data:
    postgres-password: {{ if $existing }}{{ index $existing.data "postgres-password"}}{{ else}}{{ randAlphaNum 32 | b64enc}}{{end}}
    admin-password: {{if $existing}}{{ index $existing.data "admin-password" }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
